# Generated by Django 6.0 on 2025-12-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeRack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('자전거보관소명', models.CharField(blank=True, max_length=200, null=True)),
                ('소재지도로명주소', models.CharField(blank=True, max_length=300, null=True)),
                ('소재지지번주소', models.CharField(blank=True, max_length=300, null=True)),
                ('보관대수', models.CharField(blank=True, max_length=50, null=True)),
                ('공기주입기비치여부', models.CharField(blank=True, max_length=50, null=True)),
                ('수리대설치여부', models.CharField(blank=True, max_length=50, null=True)),
                ('관리기관전화번호', models.CharField(blank=True, max_length=100, null=True)),
                ('관리기관명', models.CharField(blank=True, max_length=200, null=True)),
                ('데이터기준일자', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
