# Generated by Django 6.0 on 2025-12-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('실과명', models.CharField(blank=True, max_length=100, null=True)),
                ('법인종류', models.CharField(blank=True, max_length=100, null=True)),
                ('허가번호', models.CharField(blank=True, max_length=100, null=True)),
                ('법인명칭', models.CharField(blank=True, max_length=200, null=True)),
                ('대표자', models.CharField(blank=True, max_length=100, null=True)),
                ('법인주소', models.CharField(blank=True, max_length=300, null=True)),
                ('허가년도', models.CharField(blank=True, max_length=20, null=True)),
                ('임원', models.TextField(blank=True, null=True)),
                ('기능및목적', models.TextField(blank=True, null=True)),
                ('소관분야', models.CharField(blank=True, max_length=200, null=True)),
                ('비고', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
