# Generated by Django 4.2.26 on 2025-11-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outdoorequipment',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='outdoorequipment',
            name='longitude',
        ),
        migrations.AddField(
            model_name='outdoorequipment',
            name='equipment_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='outdoorequipment',
            name='address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outdoorequipment',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
