# Generated by Django 4.2.26 on 2025-11-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_outdoorequipment_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('reservation', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
