# Generated by Django 4.2.26 on 2025-02-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sportsfacility'),
    ]

    operations = [
        migrations.AddField(
            model_name='outdoorequipment',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outdoorequipment',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sportsfacility',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sportsfacility',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
